

#------------------------partie box ------------------------#

### first test server
GET http://localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ3OTU4ODYsImV4cCI6MTU5NDg4MjI4Nn0.ROhJwj0L36Dk7N7F24laAL8sFpg63Oy7biC8mOovp0




### recuperation des coffrets
GET http://localhost:8000/boxes
Authorization: Bearer eyJhbGciOiJIUzI1NicCI6IkpXVCJ9.eyJpYXQiOjE1OTQ2NDU2MDUsImV4cCI6MTU5NDczMjAwNX0.I-6SAjL-J6sRx18N_5x4eQVNEukS40qSmVrNeZBTTaA

### recuperation d'un coffret en fonction d'un id
GET http://localhost:8000/boxes/1

### engegistrement d'un cofret
POST http://localhost:8000/boxes
Content-Type: application/json

{
    "name": "tartiflex",
    "category_id": 1
}

### modification d'un cofret en fonction d'un id
PUT http://localhost:8000/boxes/2
Content-Type: application/json

{
    "name":"tartiflux",
    "category_id": 1

}

### supression d'un cofret en fonction d'un id
DELETE http://localhost:8000/boxes/2

#------------------------partie bouteilles ------------------------#


### recuperation des donné bouteilles
GET http://localhost:8000/bottles

### POST bouteille
POST http://localhost:8000/bottles
Content-Type: application/json

{
    "name": "chateau9dupap",
    "category_id": "1"
}

### PUT bouteille
PUT http://localhost:8000/bottles/1
Content-Type: application/json

{
    "name": "jechangelabouteille1",
    "category_id": "2"
}

### first delete 
DELETE http://localhost:8000/bottles/4

#------------------------partie catégorie ------------------------#

### recuperation des donné catégorie
GET http://localhost:8000/categories

### POST catégorie
POST http://localhost:8000/categories
Content-Type: application/json

{
    "name": "jaunelol"
}

### PUT catégorie by id
PUT http://localhost:8000/categories/5
Content-Type: application/json

{
    "name": "categorieID1changée)=)==)=)==)=)==)"
}

### delete catégorie by id
DELETE http://localhost:8000/categories/1

#------------------------partie content ------------------------#

### GET content

GET http://localhost:8000/contents


### GET content by id
GET http://localhost:8000/contents/3

### POST content

POST http://localhost:8000/contents
Content-Type: application/json

{
    "content": "jhgfrghnjk,l;jhgf du coffret rouge",
    "type": "hjfhjryjrj"
}
 
### PUT content by id

PUT http://localhost:8000/contents/2
Content-Type: application/json

{
    "content": "AAAAAAAAAAAAAAAAAAAAAAAAA",
    "type": "AAAA"
}

### DELETE content by id
DELETE http://localhost:8000/contents/5

###POST test route users/register
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "username": "TestUsername10",
    "password": "TestPassword10"
}

###POST test route users/login
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "username": "TestUsername10",
    "password": "TestPassword10"
}

#------------------------partie box_category ------------------------#


### GET box_category
GET http://localhost:8000/box_category
Content-Type: application/json

{
    "box": "Mystère",
    "category": "rouge"
}

#/* ------------------------ category_content------------------------*/#

### GET content by category
GET http://localhost:8000/categories/1/contents/difficulties/1?type=barique
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQ4ODU5ODEsImV4cCI6MTU5NDk3MjM4MX0.G3L5psISgmtVHRvfN0eoJUZ31lsIlRKExUwwnms68Wg
