#------------------------partie box ------------------------#

### first test server
GET http://localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTM2NzUxNTksImV4cCI6MTU5Mzc2MTU1OX0.jlLr8bt5-6enJq69shfQZzEMDO5sO4YEjwe8wLjhB6I




### recuperation des coffrets
GET http://localhost:8000/boxes

### recuperation d'un coffret en fonction d'un id
GET http://localhost:8000/boxes/1

### engegistrement d'un cofret
POST http://localhost:8000/boxes
Content-Type: application/json

{
    "name": "tartiflex",
    "category_id": 1
}

### modification d'un cofret en fonction d'un id
PUT http://localhost:8000/boxes/2
Content-Type: application/json

{
    "name":"tartiflux",
    "category_id": 1

}

### supression d'un cofret en fonction d'un id
DELETE http://localhost:8000/boxes/2

#------------------------partie bouteilles ------------------------#


### recuperation des donné bouteilles
GET http://localhost:8000/bottles

### POST bouteille
POST http://localhost:8000/bottles
Content-Type: application/json

{
    "name": "chateau9dupap",
    "category_id": "1"
}

### PUT bouteille
PUT http://localhost:8000/bottles/1
Content-Type: application/json

{
    "name": "jechangelabouteille1",
    "category_id": "2"
}

### first delete 
DELETE http://localhost:8000/bottles/4

#------------------------partie catégorie ------------------------#

### recuperation des donné catégorie
GET http://localhost:8000/categories

### POST catégorie
POST http://localhost:8000/categories
Content-Type: application/json

{
    "name": "jaunelol"
}

### PUT catégorie by id
PUT http://localhost:8000/categories/5
Content-Type: application/json

{
    "name": "categorieID1changée)=)==)=)==)=)==)"
}

### delete catégorie by id
DELETE http://localhost:8000/categories/1

#------------------------partie content ------------------------#

### GET content

GET http://localhost:8000/contents


### GET content by id
GET http://localhost:8000/contents/3

### POST content

POST http://localhost:8000/contents
Content-Type: application/json

{
    "content": "jhgfrghnjk,l;jhgf du coffret rouge",
    "type": "hjfhjryjrj"
}
 
### PUT content by id

PUT http://localhost:8000/contents/2
Content-Type: application/json

{
    "content": "AAAAAAAAAAAAAAAAAAAAAAAAA",
    "type": "AAAA"
}

### DELETE content by id
DELETE http://localhost:8000/contents/5

###POST test route users/register
POST http://localhost:8000/users/register
Content-Type: application/json

{
    "username": "TestUsername8",
    "password": "TestPassword8"
}

###POST test route users/login
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "username": "TestUsername8",
    "password": "TestPassword8"
}

#------------------------partie box_category ------------------------#


### GET content by id
GET http://localhost:8000/box_category
Content-Type: application/json

{
    "box": "Mystère",
    "category": "rouge"
}