#------------------------partie box ------------------------#

### first test server
GET http://localhost:8000

### recuperation des donné json
GET http://localhost:8000/boxes

### recuperation des donné json d'un id
GET http://localhost:8000/boxes/3

### POST box
POST http://localhost:8000/boxes
Content-Type: application/json

{
    "name": "nouvelle box"
}

### put box by id
PUT http://localhost:8000/boxes/5
Content-Type: application/json

{
    "name":"jai été put en 5"
}

#------------------------partie bouteilles ------------------------#


### recuperation des donné bouteilles
GET http://localhost:8000/bottles

### POST bouteille
POST http://localhost:8000/bottles
Content-Type: application/json

{
    "name": "cyfefeffyukp",
    "category_id": "1742"
}

### PUT bouteille
PUT http://localhost:8000/bottles/1
Content-Type: application/json

{
    "name": "jechangelabouteille1",
    "category_id": "2"
}